{
 "title": "Multi Cluster Kubernetes metrics",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [
  "eks",
  "metricts"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(kube_deployment_created{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "Deployment",
    "query": {
     "query": "label_values(kube_deployment_created{cluster=\"$cluster\", namespace=\"$namespace\"},deployment)"
    }
   },
   {
    "name": "Statefulset",
    "query": {
     "query": "label_values(kube_statefulset_created{cluster=\"$cluster\", namespace=\"$namespace\"},statefulset)"
    }
   },
   {
    "name": "Daemonset",
    "query": {
     "query": "label_values(kube_daemonset_created{cluster=\"$cluster\", namespace=\"$namespace\"},daemonset)"
    }
   },
   {
    "name": "Node",
    "label": "Node",
    "query": {
     "query": "label_values(kubelet_node_name{cluster=\"$cluster\"},node)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Deployment memory usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\", pod=~\"^$Deployment$Statefulset$Daemonset.*$\", node=~\"^$Node$\", pod!=\"\"}) / sum (kube_node_status_allocatable{cluster=\"$cluster\", resource=\"memory\", node=~\"^$Node.*$\"}) * 100"
    }
   ]
  },
  {
   "title": "Deployment CPU usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\", node=~\"^$Node$\"}[2m])) / sum (machine_cpu_cores{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Unavailable Replicas",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((sum(kube_deployment_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) - ((sum(kube_deployment_status_replicas_available{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)))) / ((sum(kube_deployment_status_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{cluster=\"$cluster\",namespace=~\"$namespace\",statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",namespace=~\"$namespace\",daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\", node=~\"^$Node$\", pod!=\"\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (kube_node_status_allocatable{cluster=\"$cluster\",resource=\"memory\",node=~\"^$Node.*$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\", node=~\"^$Node$\"}[2m]))"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (machine_cpu_cores{cluster=\"$cluster\",node=~\"^$Node\"})"
    }
   ]
  },
  {
   "title": "Available (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas_available{cluster=\"$cluster\",deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_status_replicas{cluster=\"$cluster\",statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_number_ready{cluster=\"$cluster\",daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))"
    }
   ]
  },
  {
   "title": "Total (cluster)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(kube_deployment_status_replicas{cluster=\"$cluster\",deployment=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_statefulset_replicas{cluster=\"$cluster\",statefulset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0)) + (sum(kube_daemonset_status_desired_number_scheduled{cluster=\"$cluster\",daemonset=~\".*$Deployment$Statefulset$Daemonset\"}) or vector(0))",
     "legendFormat": "{{ $Daemonset }}"
    }
   ]
  },
  {
   "title": "Panel Pods",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(cluster, namespace, pod, pod_ip, node, phase)(topk(1, sort_desc(kube_pod_status_phase{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"^$Deployment.*$\"})) by (pod))"
    },
    {
     "expr": "sum by(cluster, namespace, pod, node, phase, pod_ip)(kube_pod_info{cluster=\"$cluster\", namespace=~\"$namespace\", pod=~\"^$Deployment.*$\"})"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{cluster=\"$cluster\",namespace=~\"$namespace\",image!=\"\",io_kubernetes_container_name!=\"POD\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}[1m])) by (pod,node)",
     "legendFormat": "{{ node }} | {{ pod }} "
    },
    {
     "expr": "sum (kube_pod_container_resource_requests_cpu_cores{cluster=\"$cluster\",exported_namespace=~\"$namespace\",exported_pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}) by (pod,node)",
     "legendFormat": "rqst: {{ node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\", pod!=\"\"}) by (pod,node)",
     "legendFormat": "real: {{node }} | {{ pod }}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * (kubelet_volume_stats_used_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",node=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"} / kubelet_volume_stats_capacity_bytes{cluster=\"$cluster\",namespace=~\"$namespace\",node=~\"^$Node$\", persistentvolumeclaim=~\".*$Deployment$Statefulset$Daemonset.*$\"})",
     "legendFormat": "{{ persistentvolumeclaim }} | {{ node }}"
    }
   ]
  },
  {
   "title": "All processes network I/O",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\",id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}[1m])) by (pod, node)",
     "legendFormat": "-> {{ node }} | {{ pod }}"
    },
    {
     "expr": "- sum( rate (container_network_transmit_bytes_total{cluster=\"$cluster\",namespace=~\"$namespace\",id!=\"/\",pod=~\"^$Deployment$Statefulset$Daemonset.*$\",node=~\"^$Node$\"}[1m])) by (pod, node)",
     "legendFormat": "<- {{ node }} | {{ pod }}"
    }
   ]
  }
 ]
}